apiVersion: v1
kind: Secret

metadata:
  name: api-tester-secret
  namespace: api-tester

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: <your-mysql-root-password>
  DB_USERNAME: <your-db-username>
  DB_PASSWORD: <your-db-password>
  JWT_SECRET: <your-db-jwt-secret>
